### ISSUE TITLE
In Template : Change innerHTML to innerText ?

### ISSUE THREAD

**Issue by kolibril13** [kolibril13/plywood-gallery#10]
As mentioned in  https://github.com/Rickaym/plywood-gallery-for-vscode/issues/6?notification_referrer_id=NT_kwDOAqaLy7M0ODY4MDg0ODY5OjQ0NDY5MTk1
it would be good to change innerHTML to .innerText .
But this has to be tested:
What happens if the python code contains strings that contain html tags?

**Comment by lbirkert** [comment]
> What happens if the python code contains strings that contain html tags?

These will be inserted as text and not as HTML. If that's not what you want you should probably stick to insertHTML.

**Comment by lbirkert** [comment]
As tested via the firefox console this would look like following with innerText:

![image](https://user-images.githubusercontent.com/88548934/202853629-0255131e-8a67-43a5-920f-950b528d8ebd.png)

=>
![image](https://user-images.githubusercontent.com/88548934/202853624-d773c98b-26a6-4836-930c-1e4332213615.png)

**Comment by lbirkert** [comment]
And with innerHTML:

![image](https://user-images.githubusercontent.com/88548934/202853687-8b6d86c2-aef5-4134-b387-8aae46e2b1dc.png)

=>

![image](https://user-images.githubusercontent.com/88548934/202853706-2fbb3177-67bc-4219-b1d1-617d0cc66ca2.png)

**Comment by kolibril13** [comment]
Just tried innerText now. 
The problem: 
the \n linebreak does not work with innertext:
<img width="488" alt="image" src="https://user-images.githubusercontent.com/44469195/205086750-1cc5f64a-ed18-49da-9005-0c35588ae17e.png">

**Comment by lbirkert** [comment]
That is just a matter of styling. Which highlighter are you using?

**Comment by kolibril13** [comment]
I am using https://highlightjs.org/
Do you want to have a look at this issue and maybe submit a PR on that? :)

**Comment by lbirkert** [comment]
https://github.com/kolibril13/plywood-gallery/pull/14

Now manual escaping in the JS code using https://developer.mozilla.org/en-US/docs/Web/API/HTMLOptionElement/Option

**Comment by lbirkert** [comment]
This should be fixed now. Can you close this issue?
